In [24]:
import numpy as np
import pandas as pd

In [25]:
#Importing the DataSet
from google.colab import files
uploaded = files.upload()

Saving crime_incidents_messy.csv to crime_incidents_messy (1).csv

In [26]:
df= pd.read_csv("crime_incidents_messy.csv")
print("Dataset loaded successfully!")
df_original = df.copy()

Dataset loaded successfully!

In [27]:
print("\nFirst 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

print("\nDataset information:")
df.info()

print("\nColumn names:")
print(df.columns.tolist())

print("\nNumber of rows and columns:")
print(df.shape)

First 5 rows:

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,...,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
0,INC001115,asslt,Sou,Maplewood,GA,2830 Cedar Lane,170.284100,-77.500710,2024-04-16 08:45:03,OFF0078,...,Unknown,6223265920,Firearm,2,Open,No Arrest,NaN,NaN,True,Incident at 2830 Cedar Lane. Officer responded...
1,INC004706,burglary,southeast,Maplewood,OH,2361 Park Rd,29.422717,-77.167016,2022-01-11 22:03:29,OFF0059,...,NaN,241-973-4826,Firearm,3,NaN,NaN,2.0,44839.49,yes,Incident at 2361 Park Rd. Officer responded at...
2,INC002249,Homocide,Southwest,Lakewood,AZ,1067 Main St,39.411460,-98.615298,2022-04-14 11:39:24,OFF0088,...,Other,244-584-7696,KNIFE,1,CLOSED,warning,2.0,15963.38,YES,Incident at 1067 Main St. Officer responded at...
3,INC000021,Property Damage,Cen,Springfield,AZ,4713 Washington Ave,28.633439,-99.030051,2020-12-09 15:14:24,OFF0077,...,NaN,5021227484,hands,Low,Resolved,NaN,5.0,48680.14,False,Incident at 4713 Washington Ave. Officer respo...
4,INC000488,Domestc Violence,North,Lakewood,PA,1371 River Rd,34.217850,-121.614731,2021-07-24 20:08:13,OFF0083,...,M,9698766873,Unarmed,MEDIUM,Closed,Warning Issued,2.0,23513.01,YES,NaN

Last 5 rows:

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,...,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
5245,INC003247,Burglary,Nor,Springfield,OH,4434 Elm Blvd,42.576022,-79.788519,2021-12-18 17:27:18,OFF0005,...,m,534-870-3834,NaN,Medium,NaN,Arrest Made,2.0,44417.98,NaN,NaN
5246,INC000314,Vandlism,NORTHWEST,Maplewood,FL,1065 Sunset Blvd,38.941858,-108.480924,2023-06-23 04:09:19,OFF0132,...,female,NaN,NaN,2,Pending,NaN,5.0,16330.48,no,Incident at 1065 Sunset Blvd. Officer responde...
5247,INC002761,Arson,northwest,Fairview,FL,6419 Sunset Blvd,41.627732,-82.048681,2018-04-25 14:38:24,OFF0003,...,Other,796-911-1169,blunt object,4,CLOSED,NaN,4.0,13138.25,NaN,Incident at 6419 Sunset Blvd. Officer responde...
5248,INC001022,Scam,East,Maplewood,TX,9087 River Rd,28.903176,-111.840384,2023-03-29 09:54:50,OFF0028,...,female,214-897-2917,NaN,NaN,closed,arrest made,1.0,43851.12,0,Incident at 9087 River Rd. Officer responded a...
5249,INC003216,VANDALISM,west,Springfield,NY,3781 Sunset Blvd,30.859979,-78.590392,09-08-2022,OFF0102,...,NaN,NaN,NaN,CRITICAL,OPEN,arrest made,2.0,38856.84,No,Incident at 3781 Sunset Blvd. Officer responde...

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5250 non-null   object
 1   crime_type          5250 non-null   object
 2   district            5250 non-null   object
 3   city                5250 non-null   object
 4   state               5250 non-null   object
 5   address             5250 non-null   object
 6   latitude            4992 non-null   float64
 7   longitude           4961 non-null   float64
 8   incident_datetime   4910 non-null   object
 9   officer_id          5250 non-null   object
 10  officer_first_name  5250 non-null   object
 11  officer_last_name   5250 non-null   object
 12  badge_number        4938 non-null   float64
 13  suspect_id          4440 non-null   object
 14  suspect_first_name  4440 non-null   object
 15  suspect_last_name   4440 non-null   object
 16  suspect_age         4153 non-null   float64
 17  suspect_gender      3837 non-null   object
 18  suspect_race        3649 non-null   object
 19  victim_id           4993 non-null   object
 20  victim_first_name   4993 non-null   object
 21  victim_last_name    4993 non-null   object
 22  victim_age          4688 non-null   float64
 23  victim_gender       4250 non-null   object
 24  victim_phone        4194 non-null   object
 25  weapon_used         4280 non-null   object
 26  severity            4895 non-null   object
 27  case_status         4519 non-null   object
 28  resolution          4299 non-null   object
 29  num_arrests         4917 non-null   float64
 30  property_loss_usd   4814 non-null   object
 31  reported_online     4746 non-null   object
 32  notes               4181 non-null   object
dtypes: float64(6), object(27)
memory usage: 1.3+ MB

Column names:
['incident_id', 'crime_type', 'district', 'city', 'state', 'address', 'latitude', 'longitude', 'incident_datetime', 'officer_id', 'officer_first_name', 'officer_last_name', 'badge_number', 'suspect_id', 'suspect_first_name', 'suspect_last_name', 'suspect_age', 'suspect_gender', 'suspect_race', 'victim_id', 'victim_first_name', 'victim_last_name', 'victim_age', 'victim_gender', 'victim_phone', 'weapon_used', 'severity', 'case_status', 'resolution', 'num_arrests', 'property_loss_usd', 'reported_online', 'notes']

Number of rows and columns:
(5250, 33)

In [28]:
print("Missing Values in each column:")
print(df.isnull().sum())

Missing Values in each column:
incident_id              0
crime_type               0
district                 0
city                     0
state                    0
address                  0
latitude               258
longitude              289
incident_datetime      340
officer_id               0
officer_first_name       0
officer_last_name        0
badge_number           312
suspect_id             810
suspect_first_name     810
suspect_last_name      810
suspect_age           1097
suspect_gender        1413
suspect_race          1601
victim_id              257
victim_first_name      257
victim_last_name       257
victim_age             562
victim_gender         1000
victim_phone          1056
weapon_used            970
severity               355
case_status            731
resolution             951
num_arrests            333
property_loss_usd      436
reported_online        504
notes                 1069
dtype: int64

In [29]:
print("Duplicate Rows:")
print(df.duplicated().sum())

Duplicate Rows:
200

In [30]:
print("Unique Values in each column:")
for column in df.columns:
    print(f"{column}: {df[column].nunique()}")

Unique Values in each column:
incident_id: 5050
crime_type: 182
district: 131
city: 8
state: 10
address: 4895
latitude: 4750
longitude: 4726
incident_datetime: 4675
officer_id: 150
officer_first_name: 128
officer_last_name: 30
badge_number: 3631
suspect_id: 798
suspect_first_name: 30
suspect_last_name: 30
suspect_age: 218
suspect_gender: 12
suspect_race: 10
victim_id: 987
victim_first_name: 30
victim_last_name: 30
victim_age: 260
victim_gender: 12
victim_phone: 3994
weapon_used: 13
severity: 14
case_status: 12
resolution: 9
num_arrests: 11
property_loss_usd: 4592
reported_online: 10
notes: 3915

In [31]:
missing_values = ["?", "-", "NA", "N/A", "na", "n/a", "", "null", "NULL"]
df= df.replace(missing_values, np.nan)

print("Missing Values after Standarization:")
print(df.isnull().sum())

Missing Values after Standarization:
incident_id              0
crime_type               0
district                 0
city                     0
state                    0
address                  0
latitude               258
longitude              289
incident_datetime      340
officer_id               0
officer_first_name       0
officer_last_name        0
badge_number           312
suspect_id             810
suspect_first_name     810
suspect_last_name      810
suspect_age           1097
suspect_gender        1413
suspect_race          1601
victim_id              257
victim_first_name      257
victim_last_name       257
victim_age             562
victim_gender         1000
victim_phone          1056
weapon_used            970
severity               355
case_status            731
resolution             951
num_arrests            333
property_loss_usd      436
reported_online        504
notes                 1069
dtype: int64

In [32]:
duplicate_before = df.duplicated().sum()
print("Duplicate rows before cleaning:",duplicate_before)

df= df.drop_duplicates()

duplicate_after = df.duplicated().sum()
print("Duplicate rows after cleaning:",duplicate_after)

Duplicate rows before cleaning: 200
Duplicate rows after cleaning: 0

In [33]:
for column in df.select_dtypes(include="object"):
    df[column] = df[column].str.strip()

In [34]:
columns = ["crime_type", "district", "city", "state"]

for column in columns:
    df[column] = df[column].str.title()

In [38]:
df["incident_datetime"] = pd.to_datetime(
    df["incident_datetime"],
    errors="coerce"
)

In [39]:
numeric_columns = [
    "suspect_age",
    "victim_age",
    "property_loss_usd",
    "num_arrests"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

In [47]:
# Fill missing numerical values with median
numeric_columns = df.select_dtypes(include=np.number).columns

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].median())

# Fill missing text/categorical values with mode
categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    if df[column].isnull().sum() > 0:
        df[column] = df[column].fillna(df[column].mode()[0])

In [50]:
df["incident_datetime"] = df["incident_datetime"].fillna(
    df["incident_datetime"].mode()[0]
)

In [58]:
#FINAL CHECK
print("Missing values:")
print(df.isnull().sum())
print("\nTotal Missing Values:" ,df.isnull().sum().sum())

print("\nDuplicates:")
print(df.duplicated().sum())

print("\nDataset shape:")
print(df.shape)

Missing values:
incident_id           0
crime_type            0
district              0
city                  0
state                 0
address               0
latitude              0
longitude             0
incident_datetime     0
officer_id            0
officer_first_name    0
officer_last_name     0
badge_number          0
suspect_id            0
suspect_first_name    0
suspect_last_name     0
suspect_age           0
suspect_gender        0
suspect_race          0
victim_id             0
victim_first_name     0
victim_last_name      0
victim_age            0
victim_gender         0
victim_phone          0
weapon_used           0
severity              0
case_status           0
resolution            0
num_arrests           0
property_loss_usd     0
reported_online       0
notes                 0
dtype: int64

Total Missing Values: 0

Duplicates:
0

Dataset shape:
(5050, 33)